name: quiz_app
description: A Flutter quiz application

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  csv: ^5.1.1
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  intl: ^0.18.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/app_dev_mcq.csv
    - assets/data/computer_science_mcqs.csv

flutter_icons:
  android: true
  ios: true
  image_path: "flashQuiz_image.png"